permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@main
        with:
          fail-mode: true
      - name: Configure Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v30
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Pnpm - install dependencies
        run: nix run .#install
      - name: Vite - build project
        env:
          BASE_PATH: ${{ steps.pages.outputs.base_path }}
        run: nix run .#build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: frontend/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
